# -*- coding: utf-8 -*-
"""Matplotlib1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14OYh1DUutKTQEHowMuFGvEkpL4TJvfid
"""

import matplotlib.pyplot as plt


#data for plotting
x=[0,1,2,3,4,5]
y=[0,1,4,9,16,25]

#graph style for plotting a line
plt.plot(x,y)

#to display the graph
plt.show()

import matplotlib.pyplot as plt
plt.plot([1,2,3,4,])
plt.ylabel('some numbers')
plt.show()

# Bar graphs

import matplotlib.pyplot as plt

values=[5,6,3,7,2]
names=["A","B","C","D","E"]
# plt.bar(names,values,color="skyblue")
colors = ["skyblue", "lightgreen", "salmon", "gold", "lightcoral"]
plt.bar(names, values, color=colors)
plt.show()

#histogram

import matplotlib.pyplot as plt

ages=[2,5,70,40,30,45,50,45,43,40,44,60,7,23,57,28,90,77,32]

range=(0,100)
bins=10

plt.hist(ages,bins,range,color="green",histtype='bar',edgecolor='yellow',alpha=0.4)

plt.xlabel('age')

plt.ylabel('no. of people')

plt.title('My histogram')

# Scatter graph

import matplotlib.pyplot as plt
x=[0,1,2,3,4,5]
y=[0,2,6,8,4,7]

plt.scatter(x,y,label="stars",s=90,color="blue",marker="+")  # + and * works
# matplotlib ignores the edgecolor in scatter plot graph
plt.show()

#Pie chart
import matplotlib.pyplot as plt
activities=['eat','sleep','study','play']

#portion covered by each labels
slices=[2,7,8,6]

colors=['r','y','g','b']

plt.pie(slices,labels=activities,colors=colors,startangle=90,shadow=True,explode=(0,0,0.1,0),radius=1.2,autopct='%1.1f%%')

plt.legend()

import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv('sample_data/mnist_test.csv')
x=df['Model']
y=df['Price']
plt.bar(x,y)
plt.show()

#Plotting curves of given equation

import matplotlib.pyplot as plt
import numpy as np

# setting the x - coordinates
x=np.arange(0,2*(np.pi),0.1)
#setting the corresponding y-coordinates
y=np.sin(x)

plt.plot(x,y)

plt.show()

